import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import Image from "next/image";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased p-2`}
      >
        <header >
          <Image src="/sp.svg" width={235} height={40} alt="ScottishPower logo" className="m-2 absolute" />
        </header>
        <main className="min-h-screen mx-auto w-[70ch]" >
          {children}
        </main>
      </body>
    </html>
  );
}
